type: object
name: HeaderConfig
label: Header Config
fields:
  - type: string
    name: title
    label: Title
    default: ''
  - type: model
    name: titleImage
    label: 'Header image (overrides title text)'
    default: null
    models:
      - Image
  - type: number
    name: titleImageHeight
    label: Header image height
    default: 64
  - type: boolean
    name: showTitle
    label: Show title
    default: true
  - type: list
    name: navLinks
    label: Navigation links
    items:
      type: model
      models:
        - Link
